# To recreate this environment, run:
#   conda env remove -n cr-misc-function-env
#   conda env create -f environment.yml
#   conda activate cr-misc-function-env

name: cr-misc-function-env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.11.0
  - backports=1.0
  - backports.tarfile=1.2.0
  - brotli-python=1.2.0
  - cffi=2.0.0
  - colorama=0.4.6
  - crashtest=0.4.1
  - distlib=0.4.0
  - exceptiongroup=1.3.0
  - filelock=3.20.0
  - findpython=0.7.0
  - h11=0.16.0
  - h2=4.3.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.1
  - jaraco.functools=4.3.0
  - more-itertools=10.8.0
  - msgpack-python=1.1.2
  - packaging=25.0
  - pip=25.3
  - platformdirs=4.5.0
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.11.14
  - python-fastjsonschema=2.21.2
  - pywin32-ctypes=0.2.3
  - pyyaml=6.0.3
  - ruamel.yaml=0.19.1
  - ruamel.yaml.clib=0.2.15
  - setuptools=80.9.0
  - sniffio=1.3.1
  - tbb=2022.3.0
  - tomli=2.3.0
  - tomlkit=0.13.3
  - urllib3=2.5.0
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - yaml=0.2.5
  - zipp=3.23.0
  - pip:
      - annotated-types==0.7.0
      - app==0.1.0
      - asyncio==3.4.3
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - future==1.0.0
      - greenlet==3.2.3
      - idna==3.10
      - loguru==0.7.3
      - lz4==4.4.4
      - mysql-connector-python==9.3.0
      - numpy==2.3.1
      - pandas==2.3.1
      - psycopg2-binary==2.9.10
      - pyarrow==20.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyhive==0.7.0
      - pyodbc==5.2.0
      - pyodps==0.12.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - pytz==2025.2
      - requests==2.32.4
      - six==1.17.0
      - sqlalchemy==2.0.41
      - thrift==0.22.0
      - trino==0.335.0
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - win32-setctime==1.2.0
      - zstandard==0.23.0
