[mypy]
python_version = 3.11

ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
no_implicit_optional = true
strict_equality = true

# Data engineering reality
disallow_untyped_defs = false
check_untyped_defs = false

# Performance (Conda envs are big)
exclude = (?x)(^.venv/ |^.conda/ |^build/ |^dist/)
