[project]
name = "app"
version = "0.1.0"
description = "cr-misc-function"
authors = [
    {name = "caesaramBFI",email = "caesa.ram@bfi.co.id"}
]
readme = "README.md"
requires-python = ">=3.11, <3.12"
dependencies = [
    "python-dotenv (>=1.1.1,<2.0.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "pyodbc (>=5.2.0,<6.0.0)",
    "pyodps (>=0.12.4,<0.13.0)",
    "trino (>=0.335.0,<0.336.0)",
    "pyhive (>=0.7.0,<0.8.0)",
    "sqlalchemy (>=2.0.41,<3.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
    "mysql-connector-python (>=9.3.0,<10.0.0)",
    "pandas (>=2.3.1,<3.0.0)",
    "thrift (>=0.22.0,<0.23.0)",
    "oss2>=2.19.1",
    "pyarrow>=23.0.1",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "mypy>=1.13.0",
    "types-pytz",
]
